//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FideGames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public invoice()
        {
            this.invoice_detail = new HashSet<invoice_detail>();
        }
    
        public int id_invoice { get; set; }
        public int user_id { get; set; }
        public int seller { get; set; }
        public byte[] date_sell { get; set; }
        public decimal sale_total { get; set; }
        public string payment_des { get; set; }
        public Nullable<int> invoice_status { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual invoice_status invoice_status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice_detail> invoice_detail { get; set; }
        public virtual Users Users { get; set; }
    }
}
