//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FideGames.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proyectoFideGamesEntities1 : DbContext
    {
        public proyectoFideGamesEntities1()
            : base("name=proyectoFideGamesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<brand_product> brand_product { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<deparment_product> deparment_product { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<invoice> invoice { get; set; }
        public virtual DbSet<invoice_detail> invoice_detail { get; set; }
        public virtual DbSet<invoice_status> invoice_status { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<type_product> type_product { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
